const fs=require('fs'),p=require('path');
const lb64=fs.readFileSync('d:/NPM/Evolving AMCS/agent/renderer/setup.html').toString('base64');
const tb64=fs.readFileSync('d:/NPM/Evolving AMCS/agent/assets/tray.cs').toString('base64');

const L=[
"#!/usr/bin/env node",
"const h=require('http'),p=require('path'),fs=require('fs'),{spawn,exec,execSync}=require('child_process'),os=require('os');",
"const ROOT=process.cwd(),C=x=>p.join(ROOT,x);",
"const CF=C('config.json'),LG=C('logs'),LK=C('agent.lock'),PF=C('.port');",
"let dt=null,sv=null,tp=null;",
"const LH='"+lb64+"';",
"const TB='"+tb64+"';",
"function lg(...a){const t=new Date().toISOString(),m='['+t+'] '+a.join(' ');console.log(m);try{fs.mkdirSync(LG,{recursive:true});fs.appendFileSync(p.join(LG,'agent-'+t.slice(0,10)+'.log'),m+'\\n')}catch{}}",
"function lc(){try{return fs.existsSync(CF)?JSON.parse(fs.readFileSync(CF,'utf8')):null}catch{return null}}",
"function sc(c){fs.writeFileSync(CF,JSON.stringify(c,null,2))}",
"function ic(){const c=lc();return c&&c.api_url&&c.api_key}",
"function ob(u){try{if(os.platform()==='win32')exec('start \"\" \"'+u+'\"',{shell:'cmd.exe',detached:true,stdio:'ignore'});else if(os.platform()==='darwin')spawn('open',[u],{detached:true,stdio:'ignore'});else spawn('xdg-open',[u],{detached:true,stdio:'ignore'})}catch(e){lg('ob:',e.message)}}",
"async function sd(c){stopD();try{const P=require('./src/poller'),A=require('./src/api-client'),N=require('./src/notifier'),a=new A(c),pl=new P(c);lg('Daemon started');async function y(){try{const m=await a.getMachines(),pb=m.filter(m=>m.ip_address);let ok=0,er=0;for(const x of pb){const al=await pl.ping(x.ip_address);await a.submitStatus(x.id,al).catch(()=>{});try{const r=await pl.pollMachine(x),d=(r.delta_bw||0)+(r.delta_color||0);if(d>0)await a.submitReading(x.id,r);if(r.toner_levels)for(const[c,l]of Object.entries(r.toner_levels))if(l!==null&&l<=25)N.alertLowToner(x.merk,x.model,x.ip_address,c,l);ok++}catch{er++}}lg('Cycle: '+ok+' ok '+er+' failed');await a.submitLogs({ok,er,ts:new Date().toISOString()}).catch(()=>{})}catch(e){lg('Cycle err:',e.message)}}await y();dt=setInterval(y,(c.polling_interval_hours||6)*3600000);return true}catch(e){lg('D fail:',e.message);return false}}",
"function stopD(){if(dt){clearInterval(dt);dt=null;lg('Daemon stopped')}}",
"function gI(){const w=16,h=16,bpp=32,rs=Math.floor((w*bpp+31)/32)*4,ps=rs*h;const b=Buffer.alloc(6+16+40+ps);let o=0;b.writeUInt16LE(0,o);o+=2;b.writeUInt16LE(1,o);o+=2;b.writeUInt16LE(1,o);o+=2;b.writeUInt8(w,o++);b.writeUInt8(h,o++);b.writeUInt8(0,o++);b.writeUInt8(0,o++);b.writeUInt16LE(1,o);o+=2;b.writeUInt16LE(32,o);o+=2;b.writeUInt32LE(40+ps,o);o+=4;b.writeUInt32LE(22,o);o+=4;b.writeUInt32LE(40,o);o+=4;b.writeInt32LE(w,o);o+=4;b.writeInt32LE(h*2,o);o+=4;b.writeUInt16LE(1,o);o+=2;b.writeUInt16LE(32,o);o+=2;b.writeUInt32LE(0,o);o+=4;b.writeUInt32LE(ps,o);o+=4;for(let y=0;y<h;y++)for(let x=0;x<w;x++){const p=o+y*rs+x*4;b[p]=234;b[p+1]=51;b[p+2]=147;b[p+3]=255}return b}",
"function startT(port){try{let csc=null;try{const out=execSync('where csc.exe 2>nul',{encoding:'utf8',timeout:3000});csc=out.trim().split('\\n')[0];}catch{}if(!csc)try{const d=fs.readdirSync('C:\\\\Windows\\\\Microsoft.NET\\\\Framework').filter(x=>x.startsWith('v4')).sort().reverse()[0];csc='C:\\\\Windows\\\\Microsoft.NET\\\\Framework\\\\'+d+'\\\\csc.exe';if(!fs.existsSync(csc))csc=null;}catch{}if(!csc||!fs.existsSync(csc)){lg('CSC not found');return}let src=Buffer.from(TB,'base64').toString('utf8');const ico=Array.from(gI()).join(',');src=src.replace('__ICO_BYTES__','new byte[]{'+ico+'}');const tmpCs=p.join(os.tmpdir(),'pp-tray-'+process.pid+'.cs'),tmpExe=p.join(os.tmpdir(),'pp-tray-'+process.pid+'.exe');fs.writeFileSync(tmpCs,src,'utf8');lg('Compiling...');try{execSync('\"'+csc+'\" /target:winexe /out:\"'+tmpExe+'\" \"'+tmpCs+'\" /reference:System.Windows.Forms.dll /reference:System.Drawing.dll',{encoding:'utf8',timeout:30000})}catch(e){lg('CS err:',((e.stderr||e||'').toString()).slice(-200));return}if(!fs.existsSync(tmpExe)){lg('CS failed');return}lg('Tray:',fs.statSync(tmpExe).size,'bytes');tp=spawn(tmpExe,[String(port),String(process.pid)],{stdio:'ignore',windowsHide:true});tp.on('error',e=>lg('Tray err:',e.message));tp.on('exit',c=>{tp=null;lg('Tray exit:',c)});lg('Tray started')}catch(e){lg('Tray err:',e.message)}}",
"function stopT(){if(tp){try{tp.kill()}catch{}tp=null}}",
"const M={'.html':'text/html','.css':'text/css','.js':'application/javascript','.json':'application/json','.png':'image/png'};",
"function j(r,d,s=200){r.writeHead(s,{'Content-Type':'application/json'});r.end(JSON.stringify(d))}",
"const LH2=Buffer.from(LH,'base64').toString();",
"sv=h.createServer(async(req,res)=>{const u=new URL(req.url,'http://'+req.headers.host),p=u.pathname;",
"if(p==='/login'||p==='/setup.html'){res.writeHead(200,{'Content-Type':'text/html'});res.end(LH2);return}",
"if(p==='/api/login'&&req.method==='POST'){let b='';req.on('data',c=>b+=c);req.on('end',async()=>{try{const creds=JSON.parse(b);const bk=await fetch('https://printpulse-api.printpulse-api.workers.dev/api/agent/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:creds.email,password:creds.password})});const d=await bk.json();if(d.config){sc(d.config);await sd(d.config);j(res,{ok:true,config:d.config,user:d.user})}else{j(res,{error:d.error||'Login failed'},401)}}catch(e){j(res,{error:e.message},500)}});return}",
"if(p==='/api/ping')return j(res,{ok:true})",
"if(p==='/api/quit'){stopD();stopT();sv.close();try{fs.unlinkSync(LK)}catch{}try{fs.unlinkSync(PF)}catch{}process.exit(0)}",
"if(p==='/api/config'&&req.method==='GET')return j(res,lc()||{})",
"if(p==='/api/config'&&req.method==='POST'){let b='';req.on('data',c=>b+=c);req.on('end',()=>{try{sc(JSON.parse(b));j(res,{ok:true})}catch(e){j(res,{error:e.message},400)}});return}",
"if(p==='/api/config/status'){const c=lc();if(!c)return j(res,{configured:false});try{const A=require('./src/api-client');const m=await(new A(c)).getMachines();return j(res,{configured:true,tenant:c.tenant_id,machines:m.length})}catch(e){return j(res,{configured:true,error:e.message})}}",
"if(p==='/api/daemon/start'){const c=lc();return j(res,c?{ok:await sd(c)}:{error:'Not configured'},c?200:400)}",
"if(p==='/api/daemon/stop'){stopD();return j(res,{ok:true})}",
"if(p==='/api/daemon/status')return j(res,{running:dt!==null,configured:ic()})",
"if(p==='/api/discovery'){const c=lc();if(!c)return j(res,{error:'Not configured'},400);try{const S=require('./src/scanner'),A=require('./src/api-client');const r=await(new S(c)).scan();await(new A(c)).submitDiscovery(r);return j(res,{ok:true,devices:r.devices.length,printers:r.devices.filter(d=>d.snmp_result).length})}catch(e){return j(res,{error:e.message},500)}}",
"if(p==='/api/machines'){const c=lc();if(!c)return j(res,{error:'Not configured'},400);try{return j(res,await(new(require('./src/api-client'))(c)).getMachines())}catch(e){return j(res,{error:e.message},500)}}",
"if(p==='/api/logs'){try{const lf=p.join(LG,'agent-'+new Date().toISOString().slice(0,10)+'.log');return j(res,{logs:fs.existsSync(lf)?fs.readFileSync(lf,'utf8'):''})}catch{return j(res,{logs:''})}}",
"if(p==='/api/setup-complete'){const c=lc();if(c)sd(c);return j(res,{ok:true})}",
"const R=p.join(__dirname,'renderer');let fp=p==='/'?'/index.html':p;fp=p.join(R,fp);if(!fs.existsSync(fp)){res.writeHead(200,{'Content-Type':'text/html'});res.end(LH2);return}",
"try{const e=p.extname(fp).toLowerCase();res.writeHead(200,{'Content-Type':M[e]||'application/octet-stream'});res.end(fs.readFileSync(fp))}catch{j(res,{error:'Not found'},404)}",
"})",
"sv.listen(0,'127.0.0.1',()=>{const a=sv.address(),port=a.port,url='http://127.0.0.1:'+port;fs.writeFileSync(PF,String(port));lg('Dash: '+url);if(os.platform()==='win32')startT(port);if(!ic())setTimeout(()=>ob(url+'/login'),800)})",
"try{const l=fs.openSync(LK,'wx');fs.closeSync(l);process.on('exit',()=>{try{fs.unlinkSync(LK)}catch{}})}catch{if(fs.existsSync(PF)){const p=fs.readFileSync(PF,'utf8').trim();if(p)ob('http://127.0.0.1:'+p)}process.exit(0)}",
"process.on('SIGINT',()=>{stopD();stopT();sv?.close();try{fs.unlinkSync(LK)}catch{}process.exit(0)})",
"process.on('SIGTERM',()=>{stopD();stopT();sv?.close();try{fs.unlinkSync(LK)}catch{}process.exit(0)})",
"try{fs.unlinkSync(PF)}catch{}",
];
fs.writeFileSync('d:/NPM/Evolving AMCS/agent/main.js', L.join('\n'), 'utf8');
console.log('Generated:', fs.statSync('d:/NPM/Evolving AMCS/agent/main.js').size, 'bytes');
